// Mocks generated by Mockito 5.0.15 from annotations
// in weatherple/test/core/geocoding/geocoder_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:geocoding_platform_interface/src/geocoding_platform_interface.dart'
    as _i3;
import 'package:geocoding_platform_interface/src/models/models.dart' as _i5;
import 'package:geolocator/geolocator.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Geolocator].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeolocator extends _i1.Mock implements _i2.Geolocator {
  MockGeolocator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
}

/// A class which mocks [GeocodingPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeocodingPlatform extends _i1.Mock implements _i3.GeocodingPlatform {
  MockGeocodingPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Location>> locationFromAddress(String? address,
          {String? localeIdentifier}) =>
      (super.noSuchMethod(
              Invocation.method(#locationFromAddress, [address],
                  {#localeIdentifier: localeIdentifier}),
              returnValue: Future<List<_i5.Location>>.value(<_i5.Location>[]))
          as _i4.Future<List<_i5.Location>>);
  @override
  _i4.Future<List<_i5.Placemark>> placemarkFromCoordinates(
          double? latitude, double? longitude, {String? localeIdentifier}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #placemarkFromCoordinates,
                  [latitude, longitude],
                  {#localeIdentifier: localeIdentifier}),
              returnValue: Future<List<_i5.Placemark>>.value(<_i5.Placemark>[]))
          as _i4.Future<List<_i5.Placemark>>);
  @override
  String toString() => super.toString();
}
